apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: heinz
spec:
  config:
#    mode: sidecar
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint:  0.0.0.0:4317
          http:
            endpoint:  0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
#      debug:
#        {}
      otlp/jaeger:
        endpoint: my-jaeger-collector-headless:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]